Fix failure of tests caused by change in org.eclipse.jdt.core 3.39.0
Prior to this change execution of

    mvn verify -Pe4.33 -DskipUITests=false

leads to

    java.lang.AssertionError: Compiling for Java version '1.5' is no longer supported. Minimal supported version is '1.8'
            at org.eclipse.eclemma.internal.core.analysis.SourceSignatureResolverTest.setup(SourceSignatureResolverTest.java:41)

which is caused by change in
https://github.com/eclipse-jdt/eclipse.jdt.core/commit/08978b8d11524ae820c806511ff454dd1630df1f