DumpExecutionDataTest should not forcibly terminate Java processes
Forced termination sometimes causes the appearance of the dialog
"No Coverage Data"

> No coverage data has been collected during this coverage session.
> Please do not terminate the Java process manually from Eclipse.

leading to the failure of subsequent tests

```
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu bar for shell: Shell with text {No Coverage Data}
	at org.eclipse.eclemma.ui.ExportImportTest.testImport(ExportImportTest.java:34)
Caused by: org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 5000 ms.: Could not find menu bar for shell: Shell with text {No Coverage Data}
	at org.eclipse.eclemma.ui.ExportImportTest.testImport(ExportImportTest.java:34)
```