Fix failure of ContextualLaunchableTesterTest caused by change in org.eclipse.debug.ui 3.18.300 (#47)
Prior to this change execution of

    mvn verify -Pe4.31 -DskipUITests=false

leads to

    java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
            at org.eclipse.eclemma.ui.ContextualLaunchableTesterTest.error_message_should_contain_delegate_shortcut_id(ContextualLaunchableTesterTest.java:59)

which is caused by change in
https://github.com/eclipse-platform/eclipse.platform/commit/494483ea135ec22a0327ec4c9500c693555d710f